proc format;
    VALUE    $D00005F
                   01 = "Ménage d'une personne"
                   02 = "Couple sans enfants"
                   03 = "Couple avec enfants"
                   04 = "Couples avec d'autres personnes apparentées/non apparentées"
                   05 = "Parent unique sans personne(s) additionnelle(s)"
                   06 = "Autre ménage avec personnes apparentées ou non-apparentées"
                   96 = "Enchaînement valide"
                   97 = "Ne sait pas"
                   98 = "Refus"
                   99 = "Non déclaré"
                    ;
    VALUE    $D00008F
                    1 = "Possédé avec une (des) hypothèque(s) par le ménage"
                    2 = "Possédé sans hypothèque par le ménage"
                    3 = "Loué par le ménage"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE    $D00026F
                   10 = "Terre-Neuve-et-Labrador"
                   11 = "Île-du-Prince Édouard"
                   12 = "Nouvelle-Écosse"
                   13 = "Nouveau-Brunswick"
                   24 = "Québec"
                   35 = "Ontario"
                   46 = "Manitoba"
                   47 = "Saskatchewan"
                   48 = "Alberta"
                   59 = "Colombie-Britannique"
                   63 = "Capitales territoriales"
                   96 = "Enchaînement valide"
                   97 = "Ne sait pas"
                   98 = "Refus"
                   99 = "Non déclaré"
                    ;
    VALUE    $D00027F
                    1 = "1"
                    2 = "2"
                    3 = "3"
                    4 = "4 ou plus"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE    $D00028F
                   01 = "Moins de 30 ans"
                   02 = "30 à 39 ans"
                   03 = "40 à 54 ans"
                   04 = "55 à 64 ans"
                   05 = "65 à 74 ans"
                   06 = "75 ans et plus"
                   96 = "Enchaînement valide"
                   97 = "Ne sait pas"
                   98 = "Refus"
                   99 = "Non déclaré"
                    ;
    VALUE    $D00029F
                    1 = "Niveau inférieur à un diplôme d’études secondaires ou à son"
                    2 = "Diplôme d’études secondaires, certificat d'équivalence d'étu"
                    3 = "Certificat ou diplôme d’une école de métiers, d’un collège,"
                    4 = "Certificat ou diplôme universitaire"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE    $D00030F
                    1 = "Maison individuelle non attenante"
                    2 = "Maison double, en rangée, en terrasse ou duplex"
                    3 = "Appartement ou autre"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE    $D00031F
                    1 = "0 ou 1"
                    2 = "2"
                    3 = "3"
                    4 = "4 ou plus"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE    $D00032F
                    0 = "0"
                    1 = "1"
                    2 = "2"
                    3 = "3 ou plus"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE    $D00033F
                    1 = "Conjoint(e) marié(e) ou conjoint(e) de fait"
                    2 = "Célibataire, jamais marié(e)"
                    3 = "Séparé(e), veuf(ve) ou divorcé(e)"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE    $D00034F
                    1 = "Revenu d’emploi"
                    2 = "Revenu d'investissement"
                    3 = "Transferts gouvernementaux"
                    4 = "Autres revenus"
                    5 = "Toutes les sources inférieures ou égales à zéro"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE    $SEX001F
                    1 = "Homme"
                    2 = "Femme"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE    $YESN01F
                    1 = "Oui"
                    2 = "Non"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE     M00002F
          99999999.96 = "Enchaînement valide"
          99999999.97 = "Ne sait pas"
          99999999.98 = "Refus"
          99999999.99 = "Non déclaré"
                    ;
 
