proc format;
    VALUE    $D00005F
                   01 = "One person household"
                   02 = "Couple without children"
                   03 = "Couple with children"
                   04 = "Couples with other related or unrelated persons"
                   05 = "Lone parent family"
                   06 = "Other households with related or unrelated persons"
                   96 = "Valid skip"
                   97 = "Don't know"
                   98 = "Refusal"
                   99 = "Not stated"
                    ;
    VALUE    $D00008F
                    1 = "Owned with mortgage"
                    2 = "Owned without mortgage"
                    3 = "Rented"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE    $D00026F
                   10 = "Newfoundland and Labrador"
                   11 = "Prince Edward Island"
                   12 = "Nova Scotia"
                   13 = "New Brunswick"
                   24 = "Quebec"
                   35 = "Ontario"
                   46 = "Manitoba"
                   47 = "Saskatchewan"
                   48 = "Alberta"
                   59 = "British Columbia"
                   63 = "Territorial capitals"
                   96 = "Valid skip"
                   97 = "Don't know"
                   98 = "Refusal"
                   99 = "Not stated"
                    ;
    VALUE    $D00027F
                    1 = "1"
                    2 = "2"
                    3 = "3"
                    4 = "4 or more"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE    $D00028F
                   01 = "Less than 30 years"
                   02 = "30 to 39 years"
                   03 = "40 to 54 years"
                   04 = "55 to 64 years"
                   05 = "65 to 74 years"
                   06 = "75 years and over"
                   96 = "Valid skip"
                   97 = "Don't know"
                   98 = "Refusal"
                   99 = "Not stated"
                    ;
    VALUE    $D00029F
                    1 = "Less than high school diploma or its equivalent"
                    2 = "High school diploma, high school equivalency certificate, or"
                    3 = "Certificate or diploma from a trades school, college, CEGEP"
                    4 = "University certificate or diploma"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE    $D00030F
                    1 = "Single detached"
                    2 = "Double, row, terrace or duplex"
                    3 = "Apartment or other"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE    $D00031F
                    1 = "0 or 1"
                    2 = "2"
                    3 = "3"
                    4 = "4 or more"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE    $D00032F
                    0 = "0"
                    1 = "1"
                    2 = "2"
                    3 = "3 or more"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE    $D00033F
                    1 = "Married or common-law"
                    2 = "Single, never married"
                    3 = "Separated, widowed or divorced"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE    $D00034F
                    1 = "Earnings (employment income)"
                    2 = "Investment income"
                    3 = "Government transfer payments"
                    4 = "Other income"
                    5 = "All sources less than or equal to zero"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE    $SEX001F
                    1 = "Male"
                    2 = "Female"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE    $YESN01F
                    1 = "Yes"
                    2 = "No"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE     M00002F
          99999999.96 = "Valid skip"
          99999999.97 = "Don't know"
          99999999.98 = "Refusal"
          99999999.99 = "Not stated"
                    ;
 
