label variable CASEID    "Identificateur du ménage"
label variable WEIGHTD   "Poids pour le fichier journal"
label variable PROV      "Province de résidence"
label variable HHTYPE6   "Type de ménage"
label variable HHSIZE    "Taille du ménage"
label variable P0TO4     "Présence de personnes âgées de 0 à 4 ans"
label variable P5TO15    "Présence de personnes âgées de 5 à 15 ans"
label variable P16TO29   "Présence de personnes âgées de 16 à 29 ans"
label variable P30TO64   "Présence de personnes âgées de 30 à 64 ans"
label variable P65TO74   "Présence de personnes âgées de 65 à 74 ans"
label variable P75PLUS   "Présence de personnes âgées de 75 ans et plus"
label variable RP_AGEGP  "Personne de référence - Groupe d'âge"
label variable RP_GEN    "Personne de référence - Genre"
label variable RP_MAST   "Personne de référence - État civil"
label variable RP_EDUC   "Personne de référence - Niveau de scolarité"
label variable SPOUSEYN  "Présence d'un(e) conjoint(e)"
label variable SP_AGEGP  "Conjoint(e) - Groupe d'âge"
label variable SP_GEN    "Conjoint(e) - Genre"
label variable SP_EDUC   "Conjoint(e) - Niveau de scolarité"
label variable DWELTYP   "Type de logement occupé"
label variable TENURE    "Mode d'occupation du logement"
label variable NUMBEDR   "Nombre de chambres à coucher"
label variable SECRES    "Propriété d'une ou plusieurs résidences secondaires"
label variable OTHPROP   "Propriété d'autres biens immobiliers"
label variable LANDLINE  "Le ménage a un service de téléphonique conventionnel"
label variable NUMCELL   "Nombre de téléphones cellulaires"
label variable INTERNET  "Accès à Internet"
label variable INTCON_H  "Type de connexion Internet - Ligne téléphonique haute vitesse"
label variable INTCON_C  "Type de connexion Internet - Câble"
label variable INTCON_W  "Type de connexion Internet - Sans fil"
label variable INTCON_F  "Type de connexion Internet - Fibre optique"
label variable INTCON_O  "Type de connexion Internet - Autre"
label variable TVCON_C   "Le ménage a les services de télévision par câble"
label variable TVCON_S   "Le ménage a les services de télévision par une antenne parabolique"
label variable TVCON_P   "Le ménage a les services de télévision via une ligne téléphonique"
label variable TVCON_F   "Le ménage a les services de télévision par fibre-optique"
label variable TVCON_O   "Le ménage a les autres types de services de télévision"
label variable OWNVEH    "Possédait, louait ou utilisait un véhicule"
label variable OWNRV     "Le ménage possédait ou utilisait un véhicule récréatif"
label variable HHTOTINC  "Ménage - Revenu total"
label variable HHEMPIN   "Ménage - Revenu d'emploi"
label variable HHINVST   "Ménage - Revenus d'investissements"
label variable HHGTR     "Ménage - Transferts gouvernementaux"
label variable HHOTHINC  "Ménage - Autres revenus"
label variable MAJINS    "Ménage - Source principale de revenu"
label variable CC001     "Garde d'enfants"
label variable CL014     "Buanderie, services de nettoyage à sec et de blanchisserie"
label variable CL015     "Services de couturier, de cordonnier et de bijoutier"
label variable CL016     "Services vestimentaires"
label variable CL017     "Tissus pour vêtements, fil à tricoter, fil et autres articles couture"
label variable CL023     "Vêtements pour enfants (moins de 14 ans)"
label variable CL026     "Vêtements pour hommes et garçons (14 ans et plus)"
label variable CL029     "Vêtements pour femmes et filles (14 ans et plus)"
label variable CL030     "Vêtements et accessoires"
label variable CL990     "Accessoires, montres, bijoux et chaussures de sport"
label variable CS003     "Services et appareils téléphoniques"
label variable CS004     "Services téléphoniques conventionnels"
label variable CS005     "Services de téléphonies cellulaires et téléavertisseurs"
label variable CS007     "Services d'accès à Internet"
label variable CS009     "Services numériques"
label variable CS014     "Services de streaming"
label variable CS015     "Jeux d'argent en ligne"
label variable CS016     "Jeux en ligne"
label variable CS017     "Autres services numériques"
label variable CS020     "Services postaux, messagerie, livraison/autres services communication"
label variable CS021     "Téléphones et autres appareils téléphoniques"
label variable CS030     "Communications"
label variable ED002     "Éducation"
label variable ED003     "Frais de scolarité"
label variable ED030     "Manuels et fournitures scolaires"
label variable EP011     "Paiements assurance individuelle/cotisations régimes pension retraite"
label variable FD001     "Dépenses alimentaires"
label variable FD003     "Aliments achetés au magasin"
label variable FD100     "Produits de boulangerie"
label variable FD1001    "Plats d'accompagnement surgelés et autres alimentaires surgelées"
label variable FD1002    "Autres aliments cuisinés prêts-à-manger"
label variable FD1003    "Morue, plie, sole et aiglefin (frais ou congelés, crus)"
label variable FD1004    "Autres huiles et matières grasses"
label variable FD101     "Pains et petits pains et brioches non sucrés"
label variable FD102     "Pains"
label variable FD103     "Petits pains et brioches, non sucrés"
label variable FD104     "Biscuits et craquelins"
label variable FD105     "Biscuits et petits gâteaux secs sucrés"
label variable FD106     "Craquelins et pains croustillants"
label variable FD107     "Autres produits de boulangerie"
label variable FD108     "Autres produits de boulangerie (sauf congelés)"
label variable FD1100    "Services de livraison de repas prêts-à-cuisiner"
label variable FD112     "Produits de boulangerie (congelés)"
label variable FD200     "Grains et produits céréaliers"
label variable FD201     "Riz et mélanges de riz"
label variable FD202     "Riz"
label variable FD203     "Mélanges de riz"
label variable FD204     "Produits de pâtes alimentaires"
label variable FD205     "Pâtes alimentaires (fraîches ou sèches)"
label variable FD206     "Pâtes alimentaires (en conserve)"
label variable FD207     "Mélanges de pâtes alimentaires"
label variable FD208     "Autres grains et produits céréaliers"
label variable FD209     "Farine et autres mélanges à base de farine"
label variable FD212     "Céréales déjeuner/autres produits céréaliers (sauf pour nourrissons)"
label variable FD300     "Fruits, préparations à base de fruits, et noix"
label variable FD301     "Fruits frais"
label variable FD302     "Pommes (fraîches)"
label variable FD303     "Bananes et plantains (frais)"
label variable FD304     "Raisins (frais)"
label variable FD305     "Pêches et nectarines (fraîches)"
label variable FD308     "Poires (fraîches)"
label variable FD309     "Baies (fraîches)"
label variable FD315     "Agrumes (frais)"
label variable FD316     "Autres fruits (frais)"
label variable FD330     "Conserves de fruits et préparations à base de fruits"
label variable FD331     "Jus de fruits"
label variable FD350     "Autres conserves de fruits ou préparations à base de fruits"
label variable FD380     "Noix et graines"
label variable FD381     "Arachides (sans ou avec écales)"
label variable FD382     "Autres noix et graines"
label variable FD400     "Légumes et préparations à base de légumes"
label variable FD401     "Légumes frais"
label variable FD402     "Pommes de terre (sauf les patates douces)"
label variable FD403     "Tomates (fraîches)"
label variable FD404     "Laitue (fraîche)"
label variable FD405     "Chou (frais)"
label variable FD406     "Carottes (fraîches)"
label variable FD407     "Oignons (frais)"
label variable FD408     "Céleri (frais)"
label variable FD409     "Concombres (frais)"
label variable FD410     "Champignons (frais)"
label variable FD411     "Brocoli (frais)"
label variable FD412     "Autres légumes (frais)"
label variable FD418     "Poivrons (frais)"
label variable FD421     "Fines herbes fraîches"
label variable FD440     "Légumes congelés ou déshydratés"
label variable FD441     "Produits de pommes de terre (congelés)"
label variable FD442     "Autres légumes congelés"
label variable FD447     "Légumes déshydratés ou légumineuses"
label variable FD470     "Légumes en conserve et autres préparations à base de légumes"
label variable FD471     "Légumes en conserve ou embouteillés"
label variable FD478     "Salades/plats accomp. base fruits/légumes, prêt-à-manger/prêt-à-cuire"
label variable FD479     "Jus de légumes (en conserve ou embouteillé)"
label variable FD500     "Produits laitiers et oeufs"
label variable FD501     "Fromage"
label variable FD502     "Cheddar"
label variable FD503     "Mozzarella"
label variable FD504     "Fromage fondu"
label variable FD505     "Autres fromages"
label variable FD520     "Lait"
label variable FD521     "Lait entier liquide"
label variable FD522     "Lait liquide à faible teneur en gras"
label variable FD525     "Lait écrémé et autre lait liquide"
label variable FD540     "Beurre"
label variable FD541     "Crème glacée/laitiers glacés (inclut friandises laitières glacées)"
label variable FD550     "Autres produits laitiers"
label variable FD551     "Autres laits transformés"
label variable FD555     "Autres produits laitiers transformés"
label variable FD570     "Oeufs et autres produits d'oeufs"
label variable FD571     "Oeufs"
label variable FD572     "Autres produits d'oeufs"
label variable FD600     "Viande"
label variable FD601     "Viande (sauf les produits de viande transformée)"
label variable FD602     "Boeuf"
label variable FD603     "Porc"
label variable FD604     "Volaille"
label variable FD607     "Autres viandes et volaille"
label variable FD650     "Produits de viande transformée"
label variable FD651     "Bacon et jambon"
label variable FD660     "Autres produits de viande transformée"
label variable FD700     "Poissons et fruits de mer"
label variable FD701     "Poissons frais ou congelés"
label variable FD705     "Saumon (frais ou congelé, cru)"
label variable FD706     "Autres poissons (frais ou congelés, crus)"
label variable FD720     "Poissons en conserve ou autres conserves de poissons"
label variable FD721     "Thon (en conserve)"
label variable FD722     "Saumon (en conserve)"
label variable FD723     "Autres poissons (en conserve ou embouteillés)"
label variable FD724     "Poissons saumurés"
label variable FD730     "Fruits de mer et autres produits de la mer"
label variable FD731     "Crevettes et langoustines"
label variable FD732     "Autres fruits de mer et produits de la mer"
label variable FD800     "Boissons non alcoolisées et autres produits alimentaires"
label variable FD801     "Boissons non alcoolisées et préparations pour boisson"
label variable FD802     "Café et thé"
label variable FD806     "Boissons non alcoolisées"
label variable FD814     "Sucre et confiseries"
label variable FD815     "Sucre, sirops et succédanés du sucre"
label variable FD821     "Bonbons et chocolats"
label variable FD827     "Margarine, huiles et matières grasses (sauf le beurre)"
label variable FD828     "Margarine"
label variable FD829     "Huiles à friture et à salade"
label variable FD833     "Condiments, épices et vinaigres"
label variable FD834     "Mayonnaise, vinaigrettes et trempettes"
label variable FD835     "Sauces pour pâtes/pizza (en conserve, embouteillées ou déshydratées)"
label variable FD836     "Autres sauces/jus de viande (en conserve, embouteillés ou déshydratés)"
label variable FD837     "Fines herbes séchées et épices"
label variable FD838     "Ketchup"
label variable FD839     "Autres condiments (inclut le vinaigre)"
label variable FD840     "Marinades de légumes (inclut les olives)"
label variable FD841     "Aliments pour nourrissons"
label variable FD842     "Formule pour nourrissons"
label variable FD843     "Céréales et biscuits pour nourrissons"
label variable FD845     "Mets préparés surgelés"
label variable FD846     "Repas congelés"
label variable FD847     "Pizza congelée"
label variable FD850     "Soupe (sauf la soupe pour nourrisson)"
label variable FD851     "Soupe (réfrigérée, congelée, en conserve ou embouteillée)"
label variable FD852     "Préparation pour soupe (déshydratée)"
label variable FD853     "Aliments cuisinés prêts-à-manger"
label variable FD854     "Repas préparés (sauf congelés)"
label variable FD855     "Pizza (sauf congelée)"
label variable FD857     "Poisson en portion (précuit et congelé)"
label variable FD870     "Autres préparations alimentaires"
label variable FD871     "Beurre d'arachides et autres beurres de noix"
label variable FD872     "Miel"
label variable FD873     "Poudres, cristaux et sirops aromatisés pour breuvages"
label variable FD874     "Friandises glacées non-laitières"
label variable FD875     "Poudres pour desserts"
label variable FD879     "Assaisonnements (inclut le sel de table)"
label variable FD880     "Autres aliments pour cuisiner"
label variable FD881     "Tofu"
label variable FD882     "Autres repas en conserve, embouteillés ou déshydratés"
label variable FD883     "Collations"
label variable FD884     "Collations à base de pommes de terre"
label variable FD885     "Autres collations"
label variable FD899     "Aliments en conserve, en bouteille et autres aliments pour nourrissons"
label variable FD990     "Aliments achetés au restaurant"
label variable FD991     "Repas au restaurant"
label variable FD992     "Soupers au restaurant"
label variable FD993     "Dîners au restaurant"
label variable FD994     "Déjeuners au restaurant"
label variable FD995     "Collations et breuvages au restaurant"
label variable GC001     "Jeux de hasard"
label variable HC001     "Soins de santé"
label variable HC001_C   "Soins de santé - Entrevue"
label variable HC001_D   "Soins de santé - Journal"
label variable HC002     "Frais directs pour les soins de santé payés par le ménage"
label variable HC002_C   "Frais directs pour les soins de santé payés par le ménage - Entrevue"
label variable HC002_D   "Frais directs pour les soins de santé payés par le ménage - Journal"
label variable HC022     "Primes pour les régimes privés d'assurance maladie"
label variable HC025     "Primes pour les régimes privés d'assurance-accident ou invalidité"
label variable HC061     "Primes pour les régimes privés de soins de santé/d'assurance-dentaire"
label variable HE001     "Équipement ménager"
label variable HE001_C   "Équipement ménager - Entrevue"
label variable HE001_D   "Équipement ménager - Journal"
label variable HE002     "Appareils électroménagers"
label variable HE002_C   "Appareils électroménagers - Entrevue"
label variable HE002_D   "Appareils électroménagers - Journal"
label variable HE010     "Autre équipement ménager"
label variable HE010_C   "Autre équipement ménager - Entrevue"
label variable HE010_D   "Autre équipement ménager - Journal"
label variable HE017     "Entretien/location/répar./services reliés à l'ameublem./équip. ménager"
label variable HE020     "Services reliés à l'ameublement et à l'équipement ménager"
label variable HF001     "Ameublement et équipement ménagers"
label variable HF001_C   "Ameublement et équipement ménagers - Entrevue"
label variable HF001_D   "Ameublement et équipement ménagers - Journal"
label variable HF002     "Ameublement ménager"
label variable HF002_C   "Ameublement ménager - Entrevue"
label variable HF002_D   "Ameublement ménager - Journal"
label variable HO001     "Dépenses courantes"
label variable HO001_C   "Dépenses courantes - Entrevue"
label variable HO001_D   "Dépenses courantes - Journal"
label variable HO002     "Aide domestique/autr. services entretien ménager (sauf services garde)"
label variable HO003     "Dépenses pour les animaux domestiques"
label variable HO052     "Nourriture et articles pour animaux domestiques"
label variable HO050     "Achats d'animaux domestiques"
label variable HO006     "Soins vétérinaires et autres services animaliers"
label variable HO010     "Produits et équipement de nettoyage"
label variable HO014     "Articles en papier, en plastique et en aluminium"
label variable HO018     "Fournitures et services de jardinage"
label variable HO018_C   "Fournitures et services de jardinage - Entrevue"
label variable HO018_D   "Fournitures et services de jardinage - Journal"
label variable HO022     "Autres accessoires pour la maison"
label variable ME001     "Dépenses diverses"
label variable ME001_C   "Dépenses diverses - Entrevue"
label variable ME001_D   "Dépenses diverses - Journal"
label variable ME039     "Services financiers"
label variable ME040     "Autres biens et services divers"
label variable ME040_C   "Autres biens et services divers - Entrevue"
label variable ME040_D   "Autres biens et services divers - Journal"
label variable MG001     "Cadeaux en argent, pensions alimentaires et dons de bienfaisance"
label variable PC001     "Soins personnels"
label variable PC001_C   "Soins personnels - Entrevue"
label variable PC001_D   "Soins personnels - Journal"
label variable PC002     "Produits de soins personnels"
label variable PC020     "Services de soins personnels"
label variable RE001     "Loisirs"
label variable RE001_C   "Loisirs - Entrevue"
label variable RE001_D   "Loisirs - Journal"
label variable RE031     "Matériel de loisirs et services connexes"
label variable RE031_C   "Matériel de loisirs et services connexes - Entrevue"
label variable RE031_D   "Matériel de loisirs et services connexes - Journal"
label variable RE003     "Matériel de sport et équipement sportif et récréatif"
label variable RE006     "Console de jeux vidéo et accessoires"
label variable RE007     "Matériel d'art et d'artisanat"
label variable RE010     "Matériel et fournitures informatiques"
label variable RE010_C   "Matériel et fournitures informatiques - Entrevue"
label variable RE010_D   "Matériel et fournitures informatiques - Journal"
label variable RE016     "Matériel et services photographiques"
label variable RE028     "Articles de collection"
label variable RE020     "Services photographiques"
label variable RE032     "Autre équipement pour les activités récréatives"
label variable RE040     "Matériel et services de divertissement au foyer"
label variable RE040_C   "Matériel et services de divertissement au foyer - Entrevue"
label variable RE040_D   "Matériel et services de divertissement au foyer - Journal"
label variable RE041     "Matériel de divertissement au foyer"
label variable RE041_C   "Matériel de divertissement au foyer - Entrevue"
label variable RE041_D   "Matériel de divertissement au foyer - Journal"
label variable RE052     "Services de divertissement au foyer"
label variable RE060     "Services de loisir"
label variable RE061     "Divertissement"
label variable RE083     "Cinémas"
label variable RE084     "Événements sportifs et spectacles en salle"
label variable RE087     "Frais d’entrée aux musées, zoos, et autres sites"
label variable RE067     "Services de télévision et de radio par satellite"
label variable RE074     "Forfaits-voyage"
label variable RE091     "Fréquentation d’établissem. récréatifs et frais - autres activ. récr."
label variable RE120     "Caméscopes, appareils photo, pièces, accessoires et matériel connexe"
label variable RE125     "Matériel de sport/équipem. sportif et récr./serv. connexes"
label variable RE125_C   "Matériel de sport/équipem. sportif et récr./serv. connexes - Entrevue"
label variable RE125_D   "Matériel de sport/équipem. sportif et récr./serv. connexes - Journal"
label variable RE128     "Location/entretien/répar. matériel sport, équipement sportif/récréatif"
label variable RE142     "Autres services récréatifs"
label variable RE990     "Équipement de jeu extérieur et jouets pour enfants"
label variable RO001     "Matériel de lecture et autres imprimés"
label variable RO001_C   "Matériel de lecture et autres imprimés - Entrevue"
label variable RO001_D   "Matériel de lecture et autres imprimés - Journal"
label variable RO002     "Journaux"
label variable RO003     "Revues et publications périodiques"
label variable RO004     "Livres et livres numériques (sauf les manuels scolaires)"
label variable RO005     "Cartes géographiques, partitions de musique/autres produits imprimés"
label variable RO010     "Services reliés matériel lecture (reproduction, frais de bibliothèque)"
label variable RV001     "Véhicules récréatifs et services connexes"
label variable RV010     "Utilisation de véhicules récréatifs"
label variable RV020     "Achat de véhicules récréatifs"
label variable SH001     "Logement"
label variable SH002     "Logement principal du ménage"
label variable SH003     "Résidence principale louée"
label variable SH004     "Loyer"
label variable SH010     "Résidences principales appartenant au ménage"
label variable SH011     "Hypothèques payées pour la résidence principale appartenant au ménage"
label variable SH015     "Primes d'assur-propriété pour résid. princip. appartenant au ménage"
label variable SH016     "Autres dépenses pour la résidence principale appartenant au ménage"
label variable SH019     "Primes payées pour assurances reliées prêt hypothéc. résid. princip."
label variable SH030     "Eau, combustibles et électricité pour le logement principal"
label variable SH030_A   "Services d'aqueduc et d’égouts pour le logement principal"
label variable SH030_B   "Électricité pour le logement principal"
label variable SH030_C   "Gaz naturel pour le logement principal"
label variable SH034     "Autres combustibles pour le logement principal"
label variable SH040     "Autres logements"
label variable SH041     "Résidences secondaires appartenant au ménage"
label variable SH042     "Hypoth. payées résidences secondaires appartenant au ménage"
label variable SH044     "Assurance biens résidences secondaires appartenant au ménage"
label variable SH046     "Autres propriétés appartenant au ménage"
label variable SH047     "Autres propriétés appartenant au ménage"
label variable SH050     "Hébergement hors du foyer"
label variable SH060     "Services de communic./sécur. pour résid. second. appartenant au ménage"
label variable SH061     "Taxes foncières/scolaires, frais d'égout/d'aqueduc pour résid. second."
label variable SH062     "Électricité et combustibles pour résid. second. appartenant au ménage"
label variable SH082     "Réparations/entretien de toutes résid. princip. appartenant au ménage"
label variable SH990     "Autres dépenses du logement loué par l'occupant"
label variable SH991     "Frais de copropriété, taxes foncières et taxes scolaires"
label variable SH992     "Toutes les autres dépenses liées au logement possédé"
label variable TA005     "Boissons alcoolisées"
label variable TA006     "Boissons alcoolisées servies dans établissements licenciés/restaurants"
label variable TA007     "Boissons alcoolisées achetées au magasin"
label variable TA008     "Boissons alcoolisées produites par le ménage"
label variable TA018     "Prod. de tabac/boissons alcoolisées/cannabis pour usage non-thérap."
label variable TA018_C   "Prod. de tabac/boiss. alc./cannabis pour usage non-thérap. - Entrevue"
label variable TA018_D   "Prod. de tabac/boissons alc./cannabis pour usage non-thérap. - Journal"
label variable TA990     "Produits de tabac, articles pour fumeurs et cannabis pour usage non-th"
label variable TC001     "Consommation courante totale"
label variable TC001_C   "Consommation courante totale - Entrevue"
label variable TC001_D   "Consommation courante totale - Journal"
label variable TE001     "Dépenses totales"
label variable TE001_C   "Dépenses totales - Entrevue"
label variable TE001_D   "Dépenses totales - Journal"
label variable TR001     "Transport"
label variable TR001_C   "Transport - Entrevue"
label variable TR001_D   "Transport - Journal"
label variable TR002     "Transport privé"
label variable TR002_C   "Transport privé - Entrevue"
label variable TR002_D   "Transport privé - Journal"
label variable TR003     "Véhicules à usage privé"
label variable TR004     "Achat de véhicules"
label variable TR008     "Accessoires pour véhicules"
label variable TR010     "Frais pour véhicules loués à long terme"
label variable TR020     "Véhicules de location"
label variable TR080     "Utilisation de véhicules"
label variable TR080_D   "Utilisation de véhicules - Journal"
label variable TR080_C   "Utilisation de véhicules - Entrevue"
label variable TR031     "Frais d'immatriculation pour les véhicules"
label variable TR033     "Pneus, batteries et autres pièces et fournitures pour véhicules"
label variable TR034     "Réparations et entretien de véhicules"
label variable TR036     "Essence et autres carburants"
label variable TR043     "Frais de charge des véhicules électriques"
label variable TR038     "Frais de stationnement"
label variable TR039     "Permis de conduire et examens et cours de conduite"
label variable TR070     "Transport public"
label variable TR071     "Services d'utilisation, de sécurité et de communication pour véhicules"
label variable TR085     "Primes d’assurances publiques et privées pour véhicules"
label variable TX010     "Impôts sur le revenu"
