label variable CASEID    "Case Identifier"
label variable WEIGHTD   "Weight for the diary file"
label variable PROV      "Province of residence"
label variable HHTYPE6   "Household type"
label variable HHSIZE    "Household size"
label variable P0TO4     "Presence of persons aged 0 to 4 years"
label variable P5TO15    "Presence of persons aged 5 to 15 years"
label variable P16TO29   "Presence of persons aged 16 to 29 years"
label variable P30TO64   "Presence of persons aged 30 to 64 years"
label variable P65TO74   "Presence of persons aged 65 to 74 years"
label variable P75PLUS   "Presence of persons aged 75 years"
label variable RP_AGEGP  "Reference person - Age group"
label variable RP_GEN    "Reference person - Gender"
label variable RP_MAST   "Reference person - Marital status"
label variable RP_EDUC   "Reference person - Education level"
label variable SPOUSEYN  "Presence of spouse"
label variable SP_AGEGP  "Spouse - Age group"
label variable SP_GEN    "Spouse - Gender"
label variable SP_EDUC   "Spouse - Education level"
label variable DWELTYP   "Type of dwelling occupied"
label variable TENURE    "Dwelling tenure"
label variable NUMBEDR   "Number of bedrooms"
label variable SECRES    "Ownership of secondary residence(s)"
label variable OTHPROP   "Ownership of other property"
label variable LANDLINE  "Household has landline telephone service"
label variable NUMCELL   "Number of cell phones"
label variable INTERNET  "Internet access"
label variable INTCON_H  "Type of Internet connection - High-speed telephone line"
label variable INTCON_C  "Type of Internet connection - Cable"
label variable INTCON_W  "Type of Internet connection - Wireless"
label variable INTCON_F  "Type of Internet connection - Fibre-optic"
label variable INTCON_O  "Type of Internet connection - Other"
label variable TVCON_C   "Household has cable television services"
label variable TVCON_S   "Household has television services via a satellite dish"
label variable TVCON_P   "Household has television services via a phone line"
label variable OWNVEH    "Owned, leased or operated a vehicle"
label variable OWNRV     "Owned or operated a recreational vehicle"
label variable HHTOTINC  "Household - Total income"
label variable HHEMPIN   "Household - Employment income"
label variable HHINVST   "Household - Investment income"
label variable HHGTR     "Household - Government transfers"
label variable HHOTHINC  "Household - Other income"
label variable MAJINS    "Household - Major source of income"
label variable CC001     "Child care"
label variable CL014     "Laundromats, dry-cleaning and laundry services"
label variable CL015     "Services for clothing, footwear and jewellery"
label variable CL016     "Clothing services"
label variable CL017     "Clothing material, yarn, thread and other notions"
label variable CL023     "Children's wear (under 14 years)"
label variable CL026     "Men's and boys' wear (14 years and over)"
label variable CL029     "Women's and girls' wear (14 years and over)"
label variable CL030     "Clothing and accessories"
label variable CL990     "Accessories, watches, jewellery and athletic footwear"
label variable CS003     "Telephone services and equipment"
label variable CS004     "Landline telephone services"
label variable CS005     "Cell phone and pager services"
label variable CS007     "Internet access services"
label variable CS008     "Digital services"
label variable CS020     "Postal, courier, delivery and other communication services"
label variable CS021     "Telephones and other equipment"
label variable CS030     "Communications"
label variable ED002     "Education"
label variable ED003     "Tuition fees"
label variable ED030     "Textbooks and school supplies"
label variable EP011     "Personal insurance premiums and retirement/pension fund contributions"
label variable FD001     "Food expenditures"
label variable FD003     "Food purchased from stores"
label variable FD100     "Bakery products"
label variable FD1001    "Frozen side dishes and other frozen prepared food"
label variable FD1002    "Other ready-to-serve prepared food"
label variable FD1003    "Cod, flounder, sole and haddock (fresh or frozen, uncooked)"
label variable FD1004    "Other oils and fats"
label variable FD101     "Bread and unsweetened rolls and buns"
label variable FD102     "Bread"
label variable FD103     "Unsweetened rolls and buns"
label variable FD104     "Cookies and crackers"
label variable FD105     "Cookies and sweet biscuits"
label variable FD106     "Crackers and crisp breads"
label variable FD107     "Other bakery products"
label variable FD108     "Other bakery products (except frozen)"
label variable FD1100    "Ready-to-cook meal delivery services"
label variable FD112     "Frozen bakery products"
label variable FD200     "Cereal grains and cereal products"
label variable FD201     "Rice and rice mixes"
label variable FD202     "Rice"
label variable FD203     "Rice mixes"
label variable FD204     "Pasta products"
label variable FD205     "Pasta (fresh or dry)"
label variable FD206     "Pasta (canned)"
label variable FD207     "Pasta mixes"
label variable FD208     "Other cereal grains and cereal products"
label variable FD209     "Flour and flour-based mixes"
label variable FD212     "Breakfast cereal and other grain products (except infant)"
label variable FD300     "Fruit, fruit preparations and nuts"
label variable FD301     "Fresh fruit"
label variable FD302     "Apples (fresh)"
label variable FD303     "Bananas and plantains (fresh)"
label variable FD304     "Grapes (fresh)"
label variable FD305     "Peaches and nectarines (fresh)"
label variable FD308     "Pears (fresh)"
label variable FD309     "Berries (fresh)"
label variable FD315     "Citrus fruit (fresh)"
label variable FD316     "Other fruit (fresh)"
label variable FD330     "Preserved fruit and fruit preparations"
label variable FD331     "Fruit juice"
label variable FD350     "Other preserved fruit and fruit preparations"
label variable FD380     "Nuts and seeds"
label variable FD381     "Peanuts (shelled or unshelled)"
label variable FD382     "Other nuts and seeds"
label variable FD400     "Vegetables and vegetable preparations"
label variable FD401     "Fresh vegetables"
label variable FD402     "Potatoes (except sweet potatoes)"
label variable FD403     "Tomatoes (fresh)"
label variable FD404     "Lettuce (fresh)"
label variable FD405     "Cabbage (fresh)"
label variable FD406     "Carrots (fresh)"
label variable FD407     "Onions (fresh)"
label variable FD408     "Celery (fresh)"
label variable FD409     "Cucumber (fresh)"
label variable FD410     "Mushrooms (fresh)"
label variable FD411     "Broccoli (fresh)"
label variable FD412     "Other vegetables (fresh)"
label variable FD418     "Peppers (fresh)"
label variable FD421     "Fresh herbs"
label variable FD440     "Frozen and dried vegetables"
label variable FD441     "Potato products (frozen)"
label variable FD442     "Other frozen vegetables"
label variable FD447     "Dried vegetables and legumes"
label variable FD470     "Canned vegetables and other vegetable preparations"
label variable FD471     "Canned or bottled vegetables"
label variable FD478     "Ready-to-serve/cook prepared salads and side dishes, fruit/veg. based"
label variable FD479     "Vegetable juice (canned or bottled)"
label variable FD500     "Dairy products and eggs"
label variable FD501     "Cheese"
label variable FD502     "Cheddar cheese"
label variable FD503     "Mozzarella cheese"
label variable FD504     "Processed cheese"
label variable FD505     "Other cheeses"
label variable FD520     "Milk"
label variable FD521     "Fluid whole milk"
label variable FD522     "Fluid low-fat milk"
label variable FD525     "Skim and other fluid milk"
label variable FD540     "Butter"
label variable FD541     "Ice cream and ice milk (including novelties)"
label variable FD550     "Other dairy products"
label variable FD551     "Other processed milk products"
label variable FD555     "Other processed dairy products"
label variable FD570     "Eggs and other egg products"
label variable FD571     "Eggs"
label variable FD572     "Other egg products"
label variable FD600     "Meat"
label variable FD601     "Meat (except processed meat)"
label variable FD602     "Beef"
label variable FD603     "Pork"
label variable FD604     "Poultry"
label variable FD607     "Other meat and poultry"
label variable FD650     "Processed meat"
label variable FD651     "Bacon and ham"
label variable FD660     "Other processed meat"
label variable FD700     "Fish and seafood"
label variable FD701     "Fresh or frozen fish"
label variable FD705     "Salmon (fresh or frozen, uncooked)"
label variable FD706     "Other fish (fresh or frozen, uncooked)"
label variable FD720     "Canned fish or other preserved fish"
label variable FD721     "Tuna (canned)"
label variable FD722     "Salmon (canned)"
label variable FD723     "Other fish (canned or bottled)"
label variable FD724     "Cured fish"
label variable FD730     "Seafood and other marine products"
label variable FD731     "Shrimp and prawns"
label variable FD732     "Other seafood and marine products"
label variable FD800     "Non-alcoholic beverages and other food products"
label variable FD801     "Non-alcoholic beverages and beverage mixes"
label variable FD802     "Coffee and tea"
label variable FD806     "Non-alcoholic beverages"
label variable FD814     "Sugar and confectionery"
label variable FD815     "Sugar, syrups and sugar substitutes"
label variable FD821     "Candies and chocolates"
label variable FD827     "Margarine, oils and fats (excluding butter)"
label variable FD828     "Margarine"
label variable FD829     "Cooking and salad oils"
label variable FD833     "Condiments, spices and vinegars"
label variable FD834     "Mayonnaise, salad dressings and dips"
label variable FD835     "Pasta and pizza sauces (canned, bottled or dried)"
label variable FD836     "Other sauces and gravies (canned, bottled or dried)"
label variable FD837     "Dried herbs and spices"
label variable FD838     "Ketchup"
label variable FD839     "Other condiments (including vinegar)"
label variable FD840     "Pickled vegetables (including olives)"
label variable FD841     "Infant food"
label variable FD842     "Infant formula"
label variable FD843     "Infant cereals and biscuits"
label variable FD845     "Frozen prepared food"
label variable FD846     "Frozen dinners and entrees"
label variable FD847     "Frozen pizza"
label variable FD850     "Soup (except infant soup)"
label variable FD851     "Soup (chilled, frozen, canned or bottled)"
label variable FD852     "Soup (dried)"
label variable FD853     "Ready-to-serve prepared food"
label variable FD854     "Dinners and entrees (except frozen)"
label variable FD855     "Pizza (except frozen)"
label variable FD857     "Fish portions (pre-cooked and frozen)"
label variable FD870     "Other food preparations"
label variable FD871     "Peanut butter and other nut butters"
label variable FD872     "Honey"
label variable FD873     "Flavoured drink powders, crystals and syrups"
label variable FD874     "Non-dairy frozen ice treats"
label variable FD875     "Dessert powders"
label variable FD879     "Food seasonings (including table salt)"
label variable FD880     "Other materials for food preparation"
label variable FD881     "Tofu"
label variable FD882     "Other canned, bottled or dried meals"
label variable FD883     "Snack food"
label variable FD884     "Potato-based snack foods"
label variable FD885     "Other snack foods"
label variable FD899     "Canned, bottled and other infant food (including frozen)"
label variable FD990     "Food purchased from restaurants"
label variable FD991     "Restaurant meals"
label variable FD992     "Restaurant dinners"
label variable FD993     "Restaurant lunches"
label variable FD994     "Restaurant breakfasts"
label variable FD995     "Restaurant snacks and beverages"
label variable GC001     "Games of chance"
label variable HC001     "Health care"
label variable HC001_C   "Health care - Interview"
label variable HC001_D   "Health care - Diary"
label variable HC002     "Direct costs to the household for health care"
label variable HC002_C   "Direct costs to the household for health care - Interview"
label variable HC002_D   "Direct costs to the household for health care - Diary"
label variable HC022     "Private health insurance plan premiums"
label variable HC025     "Accident or disability insurance premiums"
label variable HC061     "Private health and dental plan premiums"
label variable HE001     "Household equipment"
label variable HE001_C   "Household equipment - Interview"
label variable HE001_D   "Household equipment - Diary"
label variable HE002     "Household appliances"
label variable HE002_C   "Household appliances - Interview"
label variable HE002_D   "Household appliances - Diary"
label variable HE010     "Other household equipment"
label variable HE010_C   "Other household equipment - Interview"
label variable HE010_D   "Other household equipment - Diary"
label variable HE017     "Mainten./rental/repairs/serv. related to household furnishings/equip."
label variable HE020     "Services related to household furnishings and equipment"
label variable HF001     "Household furnishings and equipment"
label variable HF001_C   "Household furnishings and equipment - Interview"
label variable HF001_D   "Household furnishings and equipment - Diary"
label variable HF002     "Household furnishings"
label variable HF002_C   "Household furnishings - Interview"
label variable HF002_D   "Household furnishings - Diary"
label variable HO001     "Household operations"
label variable HO001_C   "Household operations - Interview"
label variable HO001_D   "Household operations - Diary"
label variable HO002     "Domestic and other custodial services (excluding child care)"
label variable HO003     "Pet expenses"
label variable HO052     "Pet food and pet-related goods"
label variable HO050     "Purchase of pets"
label variable HO006     "Veterinarian and other services"
label variable HO010     "Household cleaning supplies and equipment"
label variable HO014     "Paper, plastic and foil supplies"
label variable HO018     "Garden supplies and services"
label variable HO018_C   "Garden supplies and services - Interview"
label variable HO018_D   "Garden supplies and services - Diary"
label variable HO022     "Other household supplies"
label variable ME001     "Miscellaneous expenditures"
label variable ME001_C   "Miscellaneous expenditures - Interview"
label variable ME001_D   "Miscellaneous expenditures - Diary"
label variable ME039     "Financial services"
label variable ME040     "Other miscellaneous goods and services"
label variable ME040_C   "Other miscellaneous goods and services - Interview"
label variable ME040_D   "Other miscellaneous goods and services - Diary"
label variable MG001     "Gifts of money, support payments and charitable contributions"
label variable PC001     "Personal care"
label variable PC001_C   "Personal care - Interview"
label variable PC001_D   "Personal care - Diary"
label variable PC002     "Personal care products"
label variable PC020     "Personal care services"
label variable RE001     "Recreation"
label variable RE001_C   "Recreation - Interview"
label variable RE001_D   "Recreation - Diary"
label variable RE030     "Recreational equipment and related services"
label variable RE030_D   "Recreational equipment and related services - Diary"
label variable RE030_C   "Recreational equipment and related services - Interview"
label variable RE003     "Sports, athletic and recreation equipment"
label variable RE006     "Video game systems and accessories"
label variable RE007     "Art and craft materials"
label variable RE010     "Computer equipment and supplies"
label variable RE010_C   "Computer equipment and supplies - Interview"
label variable RE010_D   "Computer equipment and supplies - Diary"
label variable RE016     "Photographic goods and services"
label variable RE020     "Photographic services"
label variable RE032     "Other recreational equipment"
label variable RE040     "Home entertainment equipment and services"
label variable RE040_C   "Home entertainment equipment and services - Interview"
label variable RE040_D   "Home entertainment equipment and services - Diary"
label variable RE041     "Home entertainment equipment"
label variable RE041_C   "Home entertainment equipment - Interview"
label variable RE041_D   "Home entertainment equipment - Diary"
label variable RE052     "Home entertainment services"
label variable RE060     "Recreational services"
label variable RE060_C   "Recreational services - Interview"
label variable RE060_D   "Recreational services - Diary"
label variable RE061     "Entertainment"
label variable RE061_C   "Entertainment - Interview"
label variable RE061_D   "Entertainment - Diary"
label variable RE062     "Movie theatres"
label variable RE063     "Live sporting and performing arts events"
label variable RE066     "Admission fees to museums, zoos, and other sites"
label variable RE067     "Television and satellite radio services"
label variable RE074     "Package trips"
label variable RE091     "Use of recreational facilities and fees - other recreational activ."
label variable RE120     "Camcorders, cameras, parts, accessories and related equipment"
label variable RE125     "Sports, athletic and recreational equipment and related services"
label variable RE125_C   "Sports, athletic and rec. equipment and related services - Interview"
label variable RE125_D   "Sports, athletic and rec. equipment and related services - Diary"
label variable RE128     "Rental, maintenance/repairs of sports, athletic/recreational equipment"
label variable RE142     "Other recreational services"
label variable RE990     "Outdoor play equipment and children's toys"
label variable RO001     "Reading materials and other printed matter"
label variable RO001_C   "Reading materials and other printed matter - Interview"
label variable RO001_D   "Reading materials and other printed matter - Diary"
label variable RO002     "Newspapers"
label variable RO003     "Magazines and periodicals"
label variable RO004     "Books and E-Books (excluding school books)"
label variable RO005     "Maps, sheet music and other printed matter"
label variable RO010     "Services related to reading materials (e.g. photocopying/library fees)"
label variable RV001     "Recreational vehicles and associated services"
label variable RV010     "Operation of recreational vehicles"
label variable RV020     "Purchase of recreational vehicles"
label variable SH001     "Shelter"
label variable SH002     "Principal accommodation"
label variable SH003     "Rented principal residence"
label variable SH004     "Rent"
label variable SH010     "Owned principal residence"
label variable SH011     "Mortgage paid on the owned principal residence"
label variable SH015     "Homeowners’ property insurance for owned principal residence"
label variable SH016     "Other expenditures for owned principal residence"
label variable SH019     "Premiums for mortgage-related insurance for owned principal residence"
label variable SH030     "Water, fuel and electricity for principal accommodation"
label variable SH030_A   "Water and sewage for principal accommodation"
label variable SH030_B   "Electricity for principal accommodation"
label variable SH030_C   "Natural gas for principal accommodation"
label variable SH034     "Other fuel for principal accommodation"
label variable SH040     "Other accommodation"
label variable SH041     "Owned secondary residences"
label variable SH042     "Mortgage paid on owned secondary residences"
label variable SH044     "Property insurance for owned secondary residences"
label variable SH046     "Other owned properties"
label variable SH047     "Other owned properties"
label variable SH050     "Accommodation away from home"
label variable SH060     "Communication and security services for owned secondary residences"
label variable SH061     "Property/school taxes, water/sewage charges for owned secondary res."
label variable SH062     "Electricity and fuel for owned secondary residences"
label variable SH082     "Repairs and maintenance of all owned principal residences"
label variable SH990     "Other expenses for rented living quarters"
label variable SH991     "Condominium fees, property taxes and school taxes"
label variable SH992     "All other expenses for the owned living quarters"
label variable TA005     "Alcoholic beverages"
label variable TA006     "Alcoholic beverages served on licensed premises and in restaurants"
label variable TA007     "Alcoholic beverages purchased from stores"
label variable TA008     "Self-made alcoholic beverages"
label variable TA018     "Tobacco products, alcoholic beverages and cannabis for non-medical use"
label variable TA018_C   "Tobacco prod./alc. beverages/cannabis for non-medical use - Interview"
label variable TA018_D   "Tobacco prod./alc. beverages/cannabis for non-medical use - Diary"
label variable TA990     "Tobacco products, smokers' supplies and cannabis for non-medical use"
label variable TC001     "Total current consumption"
label variable TC001_C   "Total current consumption - Interview"
label variable TC001_D   "Total current consumption - Diary"
label variable TE001     "Total expenditure"
label variable TE001_C   "Total expenditure - Interview"
label variable TE001_D   "Total expenditure - Diary"
label variable TR001     "Transportation"
label variable TR001_C   "Transportation - Interview"
label variable TR001_D   "Transportation - Diary"
label variable TR002     "Private transportation"
label variable TR002_C   "Private transportation - Interview"
label variable TR002_D   "Private transportation - Diary"
label variable TR003     "Private use vehicles"
label variable TR004     "Purchase of vehicles"
label variable TR008     "Accessories for vehicles"
label variable TR010     "Fees for leased vehicles"
label variable TR020     "Rented vehicles"
label variable TR030     "Vehicle operations"
label variable TR030_C   "Vehicle operations - Interview"
label variable TR030_D   "Vehicle operations - Diary"
label variable TR031     "Vehicle registration fees"
label variable TR033     "Tires, batteries, and other parts and supplies for vehicles"
label variable TR034     "Maintenance and repairs of vehicles"
label variable TR036     "Gas and other fuels"
label variable TR038     "Parking costs"
label variable TR039     "Drivers' licences and tests, and driving lessons"
label variable TR070     "Public transportation"
label variable TR071     "Vehicle operation, security and communication services"
label variable TR085     "Public and private vehicle insurance premiums"
label variable TX010     "Income taxes"
